version: '3.8'
services:

  build:
    build:
      context: ./src/build
    volumes:
      - type: volume
        source: wardir
        target: /tmp/webapps/war

  db:
    container_name: mysql
    image: mariadb
    ports:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=sSUomKm1Q7IPdWOD
      - MYSQL_DATABASE=app42
      - MYSQL_USER=tomcat
      - MYSQL_PASSWORD=yJebq3iVChtH49UU

  prod:
    container_name: tomcat
    image: tomcat:9.0
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: wardir
        target: /usr/local/tomcat/webapps
      - type: bind
        source: ./src/tomcat
        target: /usr/local/tomcat/ROOT/

volumes:
  wardir:
